name: Verify
on: [push]

jobs:
  call-workflow-passing-data:
    uses: andyw8/setup-rails/.github/workflows/verify.yml@v1
    with:
      rspec: true
      # brakeman: true
      # bundler-audit: true
